name: DEV CI/CD Pipeline

on:
  push:
    branches: [ develop", "feature/*" ]
  pull_request:
    branches: [ "develop", "feature/*" ]
  workflow_dispatch:
    inputs:
      job_to_run:
        description: 'Job to execute'
        required: true
        type: choice
        options:
          - build
jobs:
  build:
    if: ${{ github.event_name == 'push' || github.event.inputs.job_to_run == 'build' }}
    name: Build Web Application and Docker Image
    runs-on: ubuntu-latest
    #env:
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones disabled for better analysis

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 25

      - name: Install dependencies
        run: npm install

      #- name: Tests
      #  run: npm test

      - name: Build NPM Package
        run: npm run build

      - name: Docker Login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.AZURE_ACR_URL }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build and Push to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: "wiensquareacr.azurecr.io/company-website:latest"
          file: Dockerfile